#!/usr/bin/env bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[32;49m'
BLUE='\033[34;49m'
NC='\033[0m'

# Header
echo -e "${RED}
 ▗▄▄▖▗▖  ▗▖▗▄▄▖ ▗▄▄▄▖▗▄▄▖ ▗▄▄▖ ▗▖ ▗▖▗▖  ▗▖▗▖ ▗▖    ▄▄▄▄ ▄▀▀▚▖▗▄▄▄▖▗▄▄▄▖
▐▌    ▝▚▞▘ ▐▌ ▐▌▐▌   ▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▛▚▖▐▌▐▌▗▞▘       █ █  ▐▌   ▐▌   ▐▌
▐▌     ▐▌  ▐▛▀▚▖▐▛▀▀▘▐▛▀▚▖▐▛▀▘ ▐▌ ▐▌▐▌ ▝▜▌▐▛▚▖     █▀▀▀ █  ▐▌   ▐▌   ▐▌
▝▚▄▄▖  ▐▌  ▐▙▄▞▘▐▙▄▄▖▐▌ ▐▌▐▌   ▝▚▄▞▘▐▌  ▐▌▐▌ ▐▌    █▄▄▄ ▀▄▄▞▘   ▐▌   ▐▌
                                                                       
▗▄▄▖  ▗▄▖ ▗▖  ▗▖▗▄▄▄   ▗▄▖ ▗▖  ▗▖▗▄▄▄▖▗▄▄▄▄▖▗▄▄▄▖▗▄▄▖                  
▐▌ ▐▌▐▌ ▐▌▐▛▚▖▐▌▐▌  █ ▐▌ ▐▌▐▛▚▞▜▌  █     ▗▞▘▐▌   ▐▌ ▐▌                 
▐▛▀▚▖▐▛▀▜▌▐▌ ▝▜▌▐▌  █ ▐▌ ▐▌▐▌  ▐▌  █   ▗▞▘  ▐▛▀▀▘▐▛▀▚▖                 
▐▌ ▐▌▐▌ ▐▌▐▌  ▐▌▐▙▄▄▀ ▝▚▄▞▘▐▌  ▐▌▗▄█▄▖▐▙▄▄▄▖▐▙▄▄▖▐▌ ▐▌
${NC}
"


# Selections
modded () {
	lifepath () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		lifepath=(
			"Corpo"
			"Nomad"
			"Streetkid"
		)
		selectedlifepath=$(select_random "${lifepath[@]}")
		echo -e "${GREEN}Lifepath:${NC} $selectedlifepath"
	}

	apartment () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		apartment=(
			"Corpo Plaza Apartment"
			"Glen Apartment"
			"Homeless (Rent a Motel) [MOD]"
			"Japantown Apartment"
			"Kress Street Hideout"
			"Megabuilding H10"
			"Northside Apartment"
		)
		selectedapartment=$(select_random "${apartment[@]}")
		echo -e "${GREEN}Apartment:${NC} $selectedapartment"
	}

	debuffs () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		debuffs=(
			"Body must be upgraded, but only to level 14"
			"Body needs to be upgraded to level 15 before any other skills can be upgraded"
			"Can only spend attribute/perk points at levels 20/40/(50)60"
			"Can only upgrade/install new cyberware at levels 20/40/(50)60"
			"Cool must be upgraded, but only to level 14"
			"Cool needs to be upgraded to level 15 before any other skills can be upgraded"
			"Inteligence must be upgraded, but only to level 14"
			"Inteligence needs to be upgraded to level 15 before any other skills can be upgraded"
			"Metro Only"
			"No Car Stealing"
			"No Cyberware"
			"No Spending Points"
			"No Stealth"
			"No Weapon"
			"Reflexes must be upgraded, but only to level 14"
			"Reflexes needs to be upgraded to level 15 before any other skills can be upgraded"
			"Stealth Only"
			"Technical Ability must be upgraded, but only to level 14"
			"Technical Ability needs to be upgraded to level 15 before any other skills can be upgraded"
			"Used Cyberware Capacity cannot exceed half of the available capacity"
		)
		selecteddebuffs=$(select_random "${debuffs[@]}")
		echo -e "${GREEN}Debuff:${NC} $selecteddebuffs"
	}

	mods () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		mods=(
			"Always Wanted [MOD]"
			"Combat Evolved, Street Sense, NC Remembers [MOD]"
			"Dark Future"
			"EconomyPunk"
			"Enemies of Night City [MOD]"
			"Enemy Multiplier [MOD]"
			"Hardcore22V2"
			"Shattered Chrome, Chrome Plating, Flesh And Chrome [MOD]"
			"Vehicle/Life/Cyberware Insurance [MOD]"
			"Weapon Randomizer [MOD]"
		)
		selectedmods=$(select_random "${mods[@]}")
		echo -e "${GREEN}Mod:${NC} $selectedmods"
	}

	ending () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		ending=(
			"The Devil"
			"The Star"
			"The Sun"
			"Path of Least Resistance"
			"Don't Fear the Reaper"
			"The Tower"
		)
		selectedending=$(select_random "${ending[@]}")
		echo -e "${GREEN}Ending:${NC} $selectedending"
	}

	system () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		system=(
			"Arasaka Mk.1-5"
			"BioDyne Berserk"
			"Biotech Σ Mk.1-4"
			"Chrome Compressor"
			"Dynalar Sandevistan"
			"Militech Apogee"
			"Militech Berserk"
			"Militech Canto Mk.6"
			"Militech Falcon"
			"Militech Paraline Mk.1-5"
			"Moore Tech Berserk"
			"NetWatch Netdriver Mk.1"
			"QianT Warp Dancer"
			"Raven Microcyber Mk.1-3"
			"Tetratronic Rippler Mk.1-5"
			"Zetatech Berserk"
			"Zetatech Sandevistan"
		)
		selectedsystem=$(select_random "${system[@]}")
		echo -e "${GREEN}OS:${NC} $selectedsystem"
	}

	vehicle () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		vehicle=(
			"ARCH Nazaré"
			"ARCH Nazaré Itsumade"
			"ARCH Nazaré Kobold"
			"ARCH Nazaré Racer"
			"Archer Hella EC-D i360"
			"Archer Quartz Bandit"
			"Archer Quartz Sidewinder"
			"Archer Quartz Specter"
			"Archer Quartz EC-L r275"
			"Archer Quartz EC-T2 r660"
			"Brennan Apollo"
			"Brennan Apollo 650-S"
			"Chevillon Emperor 620 Ragnar"
			"Chevillon Legatus 450 Aquila"
			"Chevillon Thrax 388 Jefferson"
			"Delamain no. 21"
			"Herrera Outlaw Weiler"
			"Herrera Outlaw GTS"
			"Herrera Riptide Terrier"
			"Jackie's ARCH Heroes"
			"Mahir Supron Trailbruiser"
			"Mahir Supron FS3"
			"Mahir Supron FS3-T"
			"Makigai MaiMai P126"
			"Makigai Tanishi Kuma"
			"Makigai Tanishi T400"
			"Malina-mobile"
			"Militech Hellhound"
			"Mizutani Hozuki Hoseki"
			"Mizutani Hozuki MH2"
			"Mizutani Shion Bonewrecker"
			"Mizutani Shion Coyote"
			"Mizutani Shion Samum"
			"Mizutani Shion MZ1"
			"Mizutani Shion MZ2"
			"Mizutani Shion Targa MZT"
			"Porsche 911 Turbo (930)"
			"Porsche 911 Turbo Cabriolet (930)"
			"Quadra Sport R-7 Charon"
			"Quadra Sport R-7 Chiaroscuro"
			"Quadra Sport R-7 Sterling"
			"Quadra Sport R-7 Vigilante"
			"Quadra Turbo-R 740"
			"Quadra Turbo-R V-Tech"
			"Quadra Type-66 BULITT"
			"Quadra Type-66 Cthulhu"
			"Quadra Type-66 Hoon"
			"Quadra Type-66 Javelina"
			"Quadra Type-66 Jen Rowley"
			"Quadra Type-66 Wingate"
			"Quadra Type-66 640 TS"
			"Quadra Type-66 680 TS"
			"Quadra Type-66 Avenger"
			"Rayfield Aerondight Guinevere"
			"Rayfield Caliburn"
			"Rayfield Caliburn Mordred"
			"Rayfield Caliburn Murkmobile"
			"Scorpion's Apollo"
			"Thorton Colby Little Mule"
			"Thorton Colby Vulture"
			"Thorton Colby BARGHEST"
			"Thorton Colby C125"
			"Thorton Colby CST40"
			"Thorton Colby CX410 Gran Butte"
			"Thorton Colby CX410 Butte"
			"Thorton Galena Gecko"
			"Thorton Galena Locust"
			"Thorton Galena Rattler"
			"Thorton Galena G240"
			"Thorton Galena GA32t"
			"Thorton Mackinaw Beast"
			"Thorton Mackinaw Demiurge"
			"Thorton Mackinaw Saguaro"
			"Thorton Mackinaw MTL1"
			"Thorton Merrimac Warlock"
			"Villefort Alvarado Vato"
			"Villefort Alvarado V4F 570 Delegate"
			"Villefort Alvarado V4FH 570 Herman"
			"Villefort Columbus V340-F Freight"
			"Villefort Cortes V5000 Valor"
			"Villefort Deleon Vindicator"
			"Villefort Deleon V410-S Coupé"
			"Yaiba ARV-Q340 Semimaru"
			"Yaiba ASM-R250 Muramasa"
			"Yaiba Kusanagi Akashita"
			"Yaiba Kusanagi Peacekeeper"
			"Yaiba Kusanagi CT-3X"
		)
		selectedvehicle=$(select_random "${vehicle[@]}")
		echo -e "${GREEN}Vehicle:${NC} $selectedvehicle"
	}

	weapon () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		weapon=(
			"A-22B Chao"
			"AR Raygun Supreme 9000"
			"Achilles x-MOD2"
			"Agaou"
			"Alabai"
			"Ambition"
			"Amnesty"
			"Amstaff"
			"Archangel"
			"Ashura"
			"BFC 9000"
			"Ba Xing Chong"
			"Baby Boomer"
			"Bald Eagle"
			"Baseball Bat"
			"Baseball Bat x-MOD2"
			"Black Unicorn"
			"Bloody Maria"
			"Blue Fang"
			"Borzaya"
			"Breakthrough"
			"Butcher's Cleaver"
			"Buzzsaw"
			"Byakko"
			"Caretaker's Spade"
			"Carmen"
			"Carnage"
			"Catahoula"
			"Chaos"
			"Cheetah"
			"Chef's Knife"
			"Chesapeake"
			"Chinook"
			"Claw"
			"Claw x-MOD2"
			"Cocktail Stick"
			"Comrade's Hammer"
			"Cottonmouth"
			"Crash"
			"Crimestopper"
			"Crowbar"
			"Crowbar - Iconic"
			"Crusher"
			"Cut-o-Matic"
			"Cut-o-Matic x-MOD2"
			"D5 Copperhead"
			"D5 Sidewinder"
			"DA8 Umbra"
			"DB-2 Satara"
			"DB-2 Testera"
			"DB-4 Igla"
			"DB-4 Palica"
			"DR-12 Quasar"
			"DR-5 Nova"
			"DS1 Pulsar"
			"Death and Taxes"
			"Dezerter"
			"Divided We Stand"
			"Doom Doom"
			"Dying Night"
			"Electric Baton Alpha"
			"Electric Baton Beta"
			"Electric Baton Gamma"
			"Erebus"
			"Errata"
			"Fang"
			"Fenrir"
			"Foxhound"
			"G-58 Dian"
			"Genjiroh"
			"Gold-plated baseball bat"
			"Gris-Gris"
			"Guillotine"
			"Guillotine x-MOD2"
			"Guts"
			"Gwynbleidd"
			"HA-4 Grit"
			"HA-7 Warden"
			"HJKE-11 Yukimura"
			"HJSH-18 Masamune"
			"Hammer"
			"Hawk"
			"Headhunter"
			"Her Majesty"
			"Hercules 3AX"
			"Hypercritical"
			"JKE-X2 Kenshin"
			"Jinchu-maru"
			"Kaiken"
			"Kanabo"
			"Kappa"
			"Kappa x-MOD2"
			"Katana"
			"Knife"
			"Kolac"
			"Kongou"
			"Kukri"
			"Kyubi"
			"Kyubi x-MOD2"
			"L-69 Zhuo"
			"La Chingona Dorada"
			"Laika"
			"Lexington x-MOD2"
			"Liberty"
			"Lizzie"
			"M-10AF Lexington"
			"M-179e Achilles"
			"M-76e Omaha"
			"M2038 Tactician"
			"M2067 Defender"
			"M221 Saratoga"
			"M251s Ajax"
			"MA70 HB"
			"MA70 HB x-MOD2"
			"Machete"
			"Malorian 3516"
			"Mancinella"
			"Metel"
			"Moron Labe"
			"Mox"
			"Murphy's Law"
			"Nehan"
			"Nekomata"
			"Neurotoxin Knife"
			"Nowaki"
			"Nue"
			"O'Five"
			"Ogou"
			"Ol' Reliable"
			"Order"
			"Osprey"
			"Overture"
			"Overwatch"
			"Pariah"
			"Pit Bull"
			"Pizdets"
			"Plan B"
			"Pozhar x-MOD2"
			"Prejudice"
			"Pride"
			"Problem Solver"
			"Prototype: Shingen Mark V"
			"Psalm 11:6"
			"Punknife"
			"RT-46 Burya"
			"Raiju"
			"Rasetsu"
			"Razor"
			"Riskit"
			"Rook"
			"Rosco"
			"SOR-22"
			"SPT32 Grad"
			"Sasquatch's Hammer"
			"Satori"
			"Scalpel"
			"Scorch"
			"Senkoh LX"
			"Seraph"
			"Shigure"
			"Sir John Phallustiff"
			"Skippy"
			"Slaught-O-Matic"
			"Sovereign"
			"Sparky"
			"Steel Pipe"
			"Stinger"
			"TKI-20 Shingen"
			"Taigan"
			"Tamayura"
			"The Headsman"
			"Ticon"
			"Tinker Bell"
			"Tire Iron"
			"Tomahawk"
			"Tsumetogi"
			"Umbra x-MOD2"
			"Unity"
			"VST-37 Pozhar"
			"Volkodav"
			"Widow Maker"
			"Wild Dog"
			"Yasha"
			"Yinglong"
		)
		selectedweapon=$(select_random "${weapon[@]}")
		echo -e "${GREEN}Weapon:${NC} $selectedweapon"
	}


  echo -e "${BLUE}
You've rolled:${NC}"
	lifepath
	ending
	mods
	debuffs
	apartment
	vehicle
	system
	weapon

  echo -e "
${BLUE}Good Luck!${NC}
"
}

vanilla () {
	lifepath () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		lifepath=(
			"Corpo"
			"Nomad"
			"Streetkid"
		)
		selectedlifepath=$(select_random "${lifepath[@]}")
		echo -e "${GREEN}Lifepath:${NC} $selectedlifepath"
	}

	apartment () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		apartment=(
			"Corpo Plaza Apartment"
			"Glen Apartment"
			"Homeless"
			"Japantown Apartment"
			"Kress Street Hideout"
			"Megabuilding H10"
			"Northside Apartment"
		)
		selectedapartment=$(select_random "${apartment[@]}")
		echo -e "${GREEN}Apartment:${NC} $selectedapartment"
	}

	debuffs () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		debuffs=(
			"Body can only be upgraded to level 14"
			"Body needs to be upgraded to level 15 before any other skills can be upgraded"
			"Can only spend attribute/perk points at levels 20/40/(50)60"
			"Can only upgrade/install new cyberware at levels 20/40/(50)60"
			"Cool can only be upgraded to level 14"
			"Cool needs to be upgraded to level 15 before any other skills can be upgraded"
			"Inteligence can only be upgraded to level 14"
			"Inteligence needs to be upgraded to level 15 before any other skills can be upgraded"
			"Metro Only"
			"No Car Stealing"
			"No Cyberware"
			"No Spending Points"
			"No Stealth"
			"No Weapon"
			"Reflexes can only be upgraded to level 14"
			"Reflexes needs to be upgraded to level 15 before any other skills can be upgraded"
			"Stealth Only"
			"Technical Ability can only be upgraded to level 14"
			"Technical Ability needs to be upgraded to level 15 before any other skills can be upgraded"
			"Used Cyberware Capacity cannot exceed half of the available capacity"
		)
		selecteddebuffs=$(select_random "${debuffs[@]}")
		echo -e "${GREEN}Debuff:${NC} $selecteddebuffs"
	}

	ending () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		ending=(
			"The Devil"
			"The Star"
			"The Sun"
			"Path of Least Resistance"
			"Don't Fear the Reaper"
			"The Tower"
		)
		selectedending=$(select_random "${ending[@]}")
		echo -e "${GREEN}Ending:${NC} $selectedending"
	}

	system () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		system=(
			"Arasaka Mk.1-5"
			"BioDyne Berserk"
			"Biotech Σ Mk.1-4"
			"Chrome Compressor"
			"Dynalar Sandevistan"
			"Militech Apogee"
			"Militech Berserk"
			"Militech Canto Mk.6"
			"Militech Falcon"
			"Militech Paraline Mk.1-5"
			"Moore Tech Berserk"
			"NetWatch Netdriver Mk.1"
			"QianT Warp Dancer"
			"Raven Microcyber Mk.1-3"
			"Tetratronic Rippler Mk.1-5"
			"Zetatech Berserk"
			"Zetatech Sandevistan"
		)
		selectedsystem=$(select_random "${system[@]}")
		echo -e "${GREEN}OS:${NC} $selectedsystem"
	}

	vehicle () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		vehicle=(
			"ARCH Nazaré"
			"ARCH Nazaré Itsumade"
			"ARCH Nazaré Kobold"
			"ARCH Nazaré Racer"
			"Archer Hella EC-D i360"
			"Archer Quartz Bandit"
			"Archer Quartz Sidewinder"
			"Archer Quartz Specter"
			"Archer Quartz EC-L r275"
			"Archer Quartz EC-T2 r660"
			"Brennan Apollo"
			"Brennan Apollo 650-S"
			"Chevillon Emperor 620 Ragnar"
			"Chevillon Legatus 450 Aquila"
			"Chevillon Thrax 388 Jefferson"
			"Delamain no. 21"
			"Herrera Outlaw Weiler"
			"Herrera Outlaw GTS"
			"Herrera Riptide Terrier"
			"Jackie's ARCH Heroes"
			"Mahir Supron Trailbruiser"
			"Mahir Supron FS3"
			"Mahir Supron FS3-T"
			"Makigai MaiMai P126"
			"Makigai Tanishi Kuma"
			"Makigai Tanishi T400"
			"Malina-mobile"
			"Militech Hellhound"
			"Mizutani Hozuki Hoseki"
			"Mizutani Hozuki MH2"
			"Mizutani Shion Bonewrecker"
			"Mizutani Shion Coyote"
			"Mizutani Shion Samum"
			"Mizutani Shion MZ1"
			"Mizutani Shion MZ2"
			"Mizutani Shion Targa MZT"
			"Porsche 911 Turbo (930)"
			"Porsche 911 Turbo Cabriolet (930)"
			"Quadra Sport R-7 Charon"
			"Quadra Sport R-7 Chiaroscuro"
			"Quadra Sport R-7 Sterling"
			"Quadra Sport R-7 Vigilante"
			"Quadra Turbo-R 740"
			"Quadra Turbo-R V-Tech"
			"Quadra Type-66 BULITT"
			"Quadra Type-66 Cthulhu"
			"Quadra Type-66 Hoon"
			"Quadra Type-66 Javelina"
			"Quadra Type-66 Jen Rowley"
			"Quadra Type-66 Wingate"
			"Quadra Type-66 640 TS"
			"Quadra Type-66 680 TS"
			"Quadra Type-66 Avenger"
			"Rayfield Aerondight Guinevere"
			"Rayfield Caliburn"
			"Rayfield Caliburn Mordred"
			"Rayfield Caliburn Murkmobile"
			"Scorpion's Apollo"
			"Thorton Colby Little Mule"
			"Thorton Colby Vulture"
			"Thorton Colby BARGHEST"
			"Thorton Colby C125"
			"Thorton Colby CST40"
			"Thorton Colby CX410 Gran Butte"
			"Thorton Colby CX410 Butte"
			"Thorton Galena Gecko"
			"Thorton Galena Locust"
			"Thorton Galena G240"
			"Thorton Galena GA32t"
			"Thorton Mackinaw Beast"
			"Thorton Mackinaw Demiurge"
			"Thorton Mackinaw Saguaro"
			"Thorton Mackinaw MTL1"
			"Thorton Merrimac Warlock"
			"Villefort Alvarado Vato"
			"Villefort Alvarado V4F 570 Delegate"
			"Villefort Alvarado V4FH 570 Herman"
			"Villefort Columbus V340-F Freight"
			"Villefort Cortes V5000 Valor"
			"Villefort Deleon Vindicator"
			"Villefort Deleon V410-S Coupé"
			"Yaiba ARV-Q340 Semimaru"
			"Yaiba ASM-R250 Muramasa"
			"Yaiba Kusanagi Akashita"
			"Yaiba Kusanagi Peacekeeper"
			"Yaiba Kusanagi CT-3X"
		)
		selectedvehicle=$(select_random "${vehicle[@]}")
		echo -e "${GREEN}Vehicle:${NC} $selectedvehicle"
	}

	weapon () {
		select_random() {
				printf "%s\0" "$@" | shuf -z -n1 | tr -d '\0'
		}
		weapon=(
			"A-22B Chao"
			"AR Raygun Supreme 9000"
			"Achilles x-MOD2"
			"Agaou"
			"Alabai"
			"Ambition"
			"Amnesty"
			"Amstaff"
			"Archangel"
			"Ashura"
			"BFC 9000"
			"Ba Xing Chong"
			"Baby Boomer"
			"Bald Eagle"
			"Baseball Bat"
			"Baseball Bat x-MOD2"
			"Black Unicorn"
			"Bloody Maria"
			"Blue Fang"
			"Borzaya"
			"Breakthrough"
			"Butcher's Cleaver"
			"Buzzsaw"
			"Byakko"
			"Caretaker's Spade"
			"Carmen"
			"Carnage"
			"Catahoula"
			"Chaos"
			"Cheetah"
			"Chef's Knife"
			"Chesapeake"
			"Chinook"
			"Claw"
			"Claw x-MOD2"
			"Cocktail Stick"
			"Comrade's Hammer"
			"Cottonmouth"
			"Crash"
			"Crimestopper"
			"Crowbar"
			"Crowbar - Iconic"
			"Crusher"
			"Cut-o-Matic"
			"Cut-o-Matic x-MOD2"
			"D5 Copperhead"
			"D5 Sidewinder"
			"DA8 Umbra"
			"DB-2 Satara"
			"DB-2 Testera"
			"DB-4 Igla"
			"DB-4 Palica"
			"DR-12 Quasar"
			"DR-5 Nova"
			"DS1 Pulsar"
			"Death and Taxes"
			"Dezerter"
			"Divided We Stand"
			"Doom Doom"
			"Dying Night"
			"Electric Baton Alpha"
			"Electric Baton Beta"
			"Electric Baton Gamma"
			"Erebus"
			"Errata"
			"Fang"
			"Fenrir"
			"Foxhound"
			"G-58 Dian"
			"Genjiroh"
			"Gold-plated baseball bat"
			"Gris-Gris"
			"Guillotine"
			"Guillotine x-MOD2"
			"Guts"
			"Gwynbleidd"
			"HA-4 Grit"
			"HA-7 Warden"
			"HJKE-11 Yukimura"
			"HJSH-18 Masamune"
			"Hammer"
			"Hawk"
			"Headhunter"
			"Her Majesty"
			"Hercules 3AX"
			"Hypercritical"
			"JKE-X2 Kenshin"
			"Jinchu-maru"
			"Kaiken"
			"Kanabo"
			"Kappa"
			"Kappa x-MOD2"
			"Katana"
			"Knife"
			"Kolac"
			"Kongou"
			"Kukri"
			"Kyubi"
			"Kyubi x-MOD2"
			"L-69 Zhuo"
			"La Chingona Dorada"
			"Laika"
			"Lexington x-MOD2"
			"Liberty"
			"Lizzie"
			"M-10AF Lexington"
			"M-179e Achilles"
			"M-76e Omaha"
			"M2038 Tactician"
			"M2067 Defender"
			"M221 Saratoga"
			"M251s Ajax"
			"MA70 HB"
			"MA70 HB x-MOD2"
			"Machete"
			"Malorian 3516"
			"Mancinella"
			"Metel"
			"Moron Labe"
			"Mox"
			"Murphy's Law"
			"Nehan"
			"Nekomata"
			"Neurotoxin Knife"
			"Nowaki"
			"Nue"
			"O'Five"
			"Ogou"
			"Ol' Reliable"
			"Order"
			"Osprey"
			"Overture"
			"Overwatch"
			"Pariah"
			"Pit Bull"
			"Pizdets"
			"Plan B"
			"Pozhar x-MOD2"
			"Prejudice"
			"Pride"
			"Problem Solver"
			"Prototype: Shingen Mark V"
			"Psalm 11:6"
			"Punknife"
			"RT-46 Burya"
			"Raiju"
			"Rasetsu"
			"Razor"
			"Riskit"
			"Rook"
			"Rosco"
			"SOR-22"
			"SPT32 Grad"
			"Sasquatch's Hammer"
			"Satori"
			"Scalpel"
			"Scorch"
			"Senkoh LX"
			"Seraph"
			"Shigure"
			"Sir John Phallustiff"
			"Skippy"
			"Slaught-O-Matic"
			"Sovereign"
			"Sparky"
			"Steel Pipe"
			"Stinger"
			"TKI-20 Shingen"
			"Taigan"
			"Tamayura"
			"The Headsman"
			"Ticon"
			"Tinker Bell"
			"Tire Iron"
			"Tomahawk"
			"Tsumetogi"
			"Umbra x-MOD2"
			"Unity"
			"VST-37 Pozhar"
			"Volkodav"
			"Widow Maker"
			"Wild Dog"
			"Yasha"
			"Yinglong"
		)
		selectedweapon=$(select_random "${weapon[@]}")
		echo -e "${GREEN}Weapon:${NC} $selectedweapon"
	}


  echo -e "${BLUE}
You've rolled:${NC}"
	lifepath
	ending
	debuffs
	apartment
	vehicle
	system
	weapon

  echo -e "
${BLUE}Good Luck!${NC}
"
}

while true; do
    options=("Vanilla" "Modded" "Quit")

    echo -e "${BLUE}Select an option:${NC} "
    select opt in "${options[@]}"; do
        case $REPLY in
            1) vanilla; exit 1 ;;
            2) modded; exit 1 ;;
            3) exit 1 ;;
            *) echo "Invalid option $REPLY" >&2
        esac
    done
done
